os: linux
dist: bionic
language: node_js
node_js:
  - "12"
install:
  - npm install
cache:
  directories:
  - node_modules
script: 
#   - npm test
  - echo "npm test temporarily disabled"
notifications:
  email:
    on_pull_requests: false
    on_success: change
    on_failure: change
deploy:
  edge: true
  provider: npm
  api_token: "$NPM_TOKEN"
  cleanup: true
  access: public
  on:
    tags: true
    branch: master